### ISSUE TITLE
Repository "About" text is outdated

### ISSUE THREAD

**Issue by EliahKagan** [dmvassallo/cgrep#2]
Now that #1 is merged, the "About" text for the repository should probably be changed from:

> testing git

If you want to emphasize the demonstrative purpose of the code, I'd suggest something like:

> Demonstration of combining C and C++ code

> How to use C and C++ together in a program

If you want to emphasize what the utility actually does when run, I'd suggest something like:

> Simple console grep

**Comment by dmvassallo** [comment]
Done.
